--@STATEMENT
BEGIN
    /*################################# Inicio da execução dos comandos #################################*/
    /*Refs: PK:-02260;FK-02275;IDX:-00955;IST,UPD,DEL,COMM:-00001;C_TB:-00955;M_COL:-02260;GRAN,A_COL:-01430*/
    ISAUDE.PKG_ADMINISTRACAO.EXEC_COMANDO(-01430, 'ALTER TABLE ISAUDE.PBI_RELATORIO_PUBLICO ADD (MOSTRAR_NOME VARCHAR2(1 CHAR) DEFAULT 2 )');
    ISAUDE.PKG_ADMINISTRACAO.EXEC_COMANDO(-01430, 'ALTER TABLE ISAUDE.PBI_RELATORIO_PUBLICO ADD (URI VARCHAR2(60 CHAR) )');
    ISAUDE.PKG_ADMINISTRACAO.EXEC_COMANDO(-00001, 'COMMENT ON COLUMN ISAUDE.PBI_RELATORIO_PUBLICO.MOSTRAR_NOME IS ''Mostrar=1; Não mostrar = 2;''');
    ISAUDE.PKG_ADMINISTRACAO.EXEC_COMANDO(-00001, 'COMMENT ON COLUMN ISAUDE.PBI_RELATORIO_PUBLICO.URI IS ''URI para apresentar na URL''');

    /* Mostrar ou não mostrar o nome como titulo na apresentação do relatório agrupados. */
    ISAUDE.PKG_ADMINISTRACAO.EXEC_COMANDO(-01430, 'ALTER TABLE ISAUDE.PBI_RELATORIO ADD (MOSTRAR_NOME VARCHAR2(1 CHAR) DEFAULT 2 )');
    ISAUDE.PKG_ADMINISTRACAO.EXEC_COMANDO(-00001, 'COMMENT ON COLUMN ISAUDE.PBI_RELATORIO.MOSTRAR_NOME IS ''Mostrar=1; Não mostrar = 2;''');

    COMMIT;
END;
/