ALTER TABLE ISAUDE.PBI_RELATORIO_PUBLICO
RENAME COLUMN STATUS TO STATUS_CHAR;

ALTER TABLE ISAUDE.PBI_RELATORIO_PUBLICO
ADD STATUS NUMBER DEFAULT ON NULL 1 NOT NULL;

ALTER TABLE  ISAUDE.PBI_RELATORIO_PUBLICO SET UNUSED COLUMN STATUS_CHAR; 